<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>amp</string>
		<string>ampscript</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|div|style|script|ul|ol|form|dl))\b.*?&gt;|\{)</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|div|style|script|ul|ol|form|dl))&gt;|\})</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>HTML (AMPScript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>constants, these should always be hilighted no matter where they show up</string>
			<key>match</key>
			<string>%%(?i)(_carrierid|_channel|_city|_contactid|_countrycode|_createdby|_createddate|_datasourcename|_emailid|_firstname|_impressionregionid|_impressionregionname|_ishonordst|_istestsend|_jobsubscriberbatchid|_lastname|_listname|_mobilenumber|_modifiedby|_modifieddate|_priority|_source|_sourceobjectid|_state|_status|_utcoffset|_zipcode|__additionalemailattribute1|__additionalemailattribute2|__additionalemailattribute3|__additionalemailattribute4|__additionalemailattribute5|_messagecontext|_messagetypepreference|_replycontent|_subscriberkey|additionalinfo_|comment|comment_|emailaddr|emailname_|firstname|firstname_|ftaf_url|fullname|fullname_|jobid|lastname|lastname_|list_|listid|listsubid|member_addr|member_busname|member_city|member_country|member_postalcode|member_state|memberid|profile_center_url|replyemailaddress|replyname|subscriberid|subscription_center_url|unsub_center_url|view_email_url|xtday|xtdayofweek|xtlongdate|xtmonth|xtmonthnumeric|xtshortdate|xtyear)%%</string>
			<key>name</key>
			<string>constant.language.ampscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%{1,2}\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]%{1,2}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%{1,2}=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=%{1,2}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>include the html basic stuff</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ampscript</string>
	<key>uuid</key>
	<string>442502cb-d2b7-4d42-9da1-be3a01beb335</string>
</dict>
</plist>
