<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>amp</string>
		<string>ampscript</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|div|style|script|ul|ol|form|dl))\b.*?&gt;|\{)</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|div|style|script|ul|ol|form|dl))&gt;|\})</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>HTML (AMPScript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>constants, these should always be hilighted no matter where they show up</string>
			<key>match</key>
			<string>%+(xtmonth|xtmonthnumeric|xtday|xtdayofweek|xtyear|xtshortdate|xtlongdate|linkname|emailname_|_messagecontext|_MessageTypePreference|_replycontent|_IsTestSend|jobid|emailaddr|firstname|lastname|comment_|subscriberid|_subscriberkey|listid|list_|listsubid|messagetypepreference|mobile_number|short_code|_listname|_emailid|_JobSubscriberBatchID|_DataSourceName|replyname|replyemailaddress|memberid|member_busname|member_addr|member_city|member_state|member_postalcode|member_country|MOBILE_NUMBER|SHORT_CODE|AdditionalInfo_|__AdditionalEmailAttribute1|__AdditionalEmailAttribute2|__AdditionalEmailAttribute3|__AdditionalEmailAttribute4|__AdditionalEmailAttribute5)%+</string>
			<key>name</key>
			<string>constant.language.ampscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%+\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]%+</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%+=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=%+</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ampscript</string>
	<key>uuid</key>
	<string>442502cb-d2b7-4d42-9da1-be3a01beb335</string>
</dict>
</plist>
