<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>amp</string>
		<string>ampscript</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|div|style|script|ul|ol|form|dl))\b.*?&gt;|\{)</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|div|style|script|ul|ol|form|dl))&gt;|\})</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>HTML (AMPScript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>constants, these should always be hilighted no matter where they show up</string>
			<key>match</key>
			<string>%%(additionalinfo_|comment_|comment|emailaddr|_EmailID|emailname_|firstname_|firstname|ftaf_url|fullname_|fullname|_ImpressionRegionID|_ImpressionRegionName|_IsTestSend|jobid|_JobSubscriberBatchID|lastname_|lastname|list_|listid|_ListName|listsubid|member_addr|member_busname|member_city|member_country|memberid|member_postalcode|member_state|_messagecontext|_messagetypepreference|_replycontent|profile_center_url|replyname|replyemailaddress|subscriberid|_subscriberkey|subscription_center_url|unsub_center_url|xtday|xtdayofweek|xtlongdate|xtmonth|xtmonthnumeric|xtshortdate|xtyear|view_email_url|_CarrierID|_Channel|_City|_ContactID|_CountryCode|_CreatedBy|_CreatedDate|_FirstName|_IsHonorDST|_LastName|_MobileNumber|_ModifiedBy|_ModifiedDate|_Priority|_Source|_SourceObjectID|_State|_Status|_UTCOffset|_ZipCode|__AdditionalEmailAttribute1|__AdditionalEmailAttribute2|__AdditionalEmailAttribute3|__AdditionalEmailAttribute4|__AdditionalEmailAttribute5)%%</string>
			<key>name</key>
			<string>constant.language.ampscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%{1,2}\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]%{1,2}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%{1,2}=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.ampscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>=%{1,2}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.ampscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.ampscript.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ampscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>include the html basic stuff</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ampscript</string>
	<key>uuid</key>
	<string>442502cb-d2b7-4d42-9da1-be3a01beb335</string>
</dict>
</plist>
